# Generated by Django 5.1.7 on 2025-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bothEars", models.BooleanField()),
                ("score", models.IntegerField()),
                ("timestamp", models.CharField(max_length=10)),
            ],
        ),
    ]
