# Generated by Django 5.1.7 on 2025-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digit_span", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("music", models.CharField(max_length=10)),
                ("bothEars", models.BooleanField()),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
