# Generated by Django 5.1.7 on 2025-03-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digit_span", "0002_test_delete_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="round",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
