# Generated by Django 5.1.7 on 2025-03-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digit_span", "0003_playercount_test_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="bothEars",
            field=models.CharField(max_length=5),
        ),
    ]
